import React from 'react'

import './Home.css'

export default function Home() {
  return (
    <div>
      <div className="back-splash-container">
        <div className="home-back-splash" style={{background: 'url(/homeBacksplash.jpg) no-repeat center center fixed'}}></div>
        <div className="back-splash-message">Taylor Williams</div>
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div><div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
      <div>
        Yes
      </div>
    </div>
  )
}